title: 'BitDevs NYC'
tagline: 'BitDevs is a community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Meetup', url: 'https://www.meetup.com/BitDevsNYC/', external: true}
